server:
  port: 8080
  servlet:
    session:
      timeout: 3600s
dubbo:
  application:
    name: worker-manage
  registry:
    address: zookeeper://192.168.85.132:2181

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      serviceUrl: http://localhost:8761/eureka/
spring:
  rabbitmq:
    host: 192.168.85.132
    username: guest
    password: guest
  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS       默认
    #JsonInclude.Include.NON_DEFAULT   属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY     属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL      属性为NULL  不序列化
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd

